name: 'build-ios'
runs:
  using: "composite"
  steps:
    - name: Set up Gradle
      uses: ./.github/actions/setup-gradle
    - name: Set up Xcode
      uses: ./.github/actions/setup-xcode
    - name: Build iOS
      shell: bash
      run: |
        set -Eeuo pipefail
        cd ios
        tuist build App
        cd ..
    - name: Artifacts
      uses: actions/upload-artifact@v4
      if: always() # Ensure all artifacts are collected, even after errors
      with:
        name: iOS Build
        path: |
          ~/**/tuist/logs/*.log
          ~/**/Xcode/DerivedData/**/*.app
          ~/**/Xcode/DerivedData/**/*.dSYM
          **/build
          **/secrets.properties
          **/GoogleService-Info.plist