name: 'setup-xcode'
inputs:
  cache-key:
    required: true
runs:
  using: "composite"
  steps:
    - name: Set up Xcode version
      shell: bash
      run: |
        set -Eeuo pipefail
        sudo xcode-select -s /Applications/Xcode_16.2.app
    - name: Set up Xcode
      uses: irgaly/xcode-cache@v1
      with:
        key: xcode-cache-derived-data-${{ inputs.cache-key }}-${{ github.workflow }}-${{ github.sha }}
        restore-keys: xcode-cache-derived-data-${{ inputs.cache-key }}-${{ github.workflow }}
        swiftpm-cache-key: swiftpm-cache-key-${{ inputs.cache-key }}-${{ hashFiles( '**/Package.resolved' ) }}